<TABLE WIDTH="100%" BORDER="0" CELLSPACING="0" CELLPADDING="0">
	  <TR>
        <TD WIDTH="50%" VALIGN="TOP"><IMG SRC="/images/shim.gif" WIDTH="10" HEIGHT="1"></TD>
		<TD WIDTH="760" ALIGN="CENTER" VALIGN="TOP" CLASS="footer"><IMG SRC="/images/shim.gif" WIDTH="760" HEIGHT="1"><BR>
		  <A HREF="/sitemap/index.shtml" target="_top"><B>Sitemap</B></A> |
		  <A HREF="/contact/directions/index.shtml" target="_top"><B>Directions</B></A> |
		  <A HREF="/specials/subscribe/index.shtml" target="_top"><B>Subscribe Now</B></A> |
		  <A HREF="#" target="_top"><B>Privacy Policy</B></A> |
		  <A HREF="#" target="_top"><B>Low Price Guarantee</B></A> |
		  <A HREF="/contact/info/index.shtml" target="_top"><B>Contact Us</B></A><BR>
		  TM &amp; &copy; 2001 Guy Schmidt, Inc. All rights reserved.<BR><BR></TD>
		<TD WIDTH="50%" VALIGN="TOP"><IMG SRC="/images/shim.gif" WIDTH="10" HEIGHT="1"></TD>
	  </TR>
    </TABLE>