<SCRIPT LANGUAGE="Javascript" SRC="/fade.js"></SCRIPT>
<TABLE WIDTH="100%" BORDER="0" CELLSPACING="0" CELLPADDING="0">
	  <TR>
		<TD WIDTH="760" ALIGN="CENTER" VALIGN="TOP" CLASS="footer"><IMG SRC="/images/shim.gif" WIDTH="760" HEIGHT="1"><BR>
		  <A HREF="/sitemap/index.shtml" NAME="stream1" CLASS="fade">Sitemap</A> |
		  <A HREF="/contact/directions/index.shtml" NAME="stream2" CLASS="fade">Directions</A> |
		  <A HREF='javascript:open_new_win2("/specials/subscribe/index.shtml?intBack=1")' NAME="stream3" CLASS="fade">Subscribe Now</A> |
		  <A HREF="/finance/quote/index.shtml" NAME="stream5" CLASS="fade">Quik Quote</A> |
		  <A HREF="/aboutus/policy/index.shtml" NAME="stream4" CLASS="fade">Privacy Policy</A> |
		  <A HREF="/contact/info/index.shtml" NAME="stream6" CLASS="fade">Contact Us</A><BR>
		  TM &amp; &copy; 2001 Guy Schmidt, Inc. All rights reserved.<BR><BR></TD>
		<TD WIDTH="100%" VALIGN="TOP"><IMG SRC="/images/shim.gif" WIDTH="10" HEIGHT="1"></TD>
	  </TR>
    </TABLE>