<SCRIPT LANGUAGE="JavaScript">
	function open_new_win(url)
  {
    newWindow = window.open(url,"popup","width=800,height=450,RESIZABLE=NO,SCROLLBARS=YES,STATUS=YES,MENUBAR=NO,TOOLBAR=NO")
  } // open_new_win()
</SCRIPT>
<SCRIPT LANGUAGE="JavaScript">
	function open_new_win2(url)
  {
    newWindow = window.open(url,"popup","width=400,height=270,RESIZABLE=NO,SCROLLBARS=NO,STATUS=YES,MENUBAR=NO,TOOLBAR=NO")
  } // open_new_win()
</SCRIPT>
<SCRIPT LANGUAGE="JavaScript">
	function open_new_win3(url)
  {
    newWindow = window.open(url,"popup","width=490,height=420,RESIZABLE=YES,SCROLLBARS=YES,STATUS=YES,MENUBAR=NO,TOOLBAR=NO")
  } // open_new_win()
</SCRIPT>